import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "prueba tecnica",
  description: "Generated by Andres cavadia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
